# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Junhyun Park
title: M.S Candidate
email: junhyunpark1995@gmail.com
website: chivalrous-feta-21d.notion.site/6523a48cf4ec45da940e536b57d61d9f
# website: www.github.com/jundev1l2l/jundev1l2l.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
linkedin_username: junhyun-park-428b50226
github_username:  jundev1l2l
# twitter_username: 
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: Junhyun Park
# flickr_username: jekyll
# instagram_username: junhyun_1l2l
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# # Additional icon links
# additional_links:
# - title: Portfolio (Notion)
#   icon: far fa-brain
#   url: https://chivalrous-feta-21d.notion.site/6523a48cf4ec45da940e536b57d61d9f
# - title: LIM Lab
#   icon: far fa-brain
#   url: https://sites.google.com/view/sungbin/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpeg
about_content: | # this will include new lines to allow paragraphs
  M.S. Candidate (~2022.08) at UNIST, Graduate School of Artificial Intelligence, advised by Sungbin Lim.
  
  My research interest is on Machine learning and Deep Learning, including
  - Task Adaptation (Meta-Learning, Continual Learning)
  - Stochastic Decision-Making Problem (Reinforcement Learning, Multi-Armed Bandit)
  - Uncertainty Estimation (Bayesian Deep Learning, Out-of-distribution, Domain Shift)
  
  I used to study Chemistry, Physics, and Materials Science, but since 2020 I have devoted myself to AI.

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

#   - title: Experience # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: left
#         title: The Boring Company
#         link: boringcompany.com
#         # link_text: boringcompany.com
#         sub_title: Senior Network System Administrator
#         caption: November 2017 - Present
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#             Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ulsan National Institute of Science and Technology (UNIST)
        caption: 2020.9 - 2022.08
        sub_title: M.S in Artificial Intelligence
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#         description: | # this will include new lines to allow paragraphs
#           During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

#           I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: left
        title: Seoul National University (SNU)
        caption: 2014.03 - 2019.02
        sub_title: B.S in Materials Science and Engineering

      - layout: left
        title: Korea Science Academy (KSA)
        caption: 2011.03 - 2014.02
        sub_title: Chemistry & Physics
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#         description: | # this will include new lines to allow paragraphs
#           During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

#           I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Experience
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University (SNU)
        caption: 2019.03 - 2020.01
        sub_title: Combined M.S & Ph.D in Carbon Nanomaterials Design Laboratory (Withdrawal)
#         quote: >
#           Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#         description: | # this will include new lines to allow paragraphs
#           During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

#           I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

#   - title: A Little More About Me
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
